variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  GCS_BUCKET: sizer.ocs.ninja
  GCS_PROJECT: apt-quarter-272014

default:
  image:
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
  before_script:
    - apk update && apk add -u npm
    - cd "$CI_PROJECT_DIR"
    - npm install
  artifacts:
    paths:
      - "*.html"
      - build/
    expire_in: 1 month
  cache:
    paths:
      - node_modules

stages:
  - test
  - build
  - deploy

eslint:
  stage: test
  script:
    - ./node_modules/.bin/eslint --ext ".js,.ts" src/

build:
  stage: build
  script:
    - if [[ "$CI_COMMIT_BRANCH" == "develop" ]]; then PRE_BUILD="beta"; fi
    - npm run ${PRE_BUILD}build-upstream

push-to-google-storage:
  stage: deploy
  only:
    - main
    - develop
  script:
    - ls -al && ls -al build
    - echo -n "${GCS_SA_KEY}" | base64 -d > /tmp/key.json
    - /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=/tmp/key.json --project="${GCS_PROJECT}"
    - rm /tmp/key.json
    - if [[ "$CI_COMMIT_BRANCH" == "develop" ]]; then GCP_DIR="beta/"; fi
    - /google-cloud-sdk/bin/gsutil -m cp -r "${CI_PROJECT_DIR}/*.html" "gs://${GCS_BUCKET}/${GCP_DIR}"
    - /google-cloud-sdk/bin/gsutil -m cp -r "${CI_PROJECT_DIR}/lib/*" "gs://${GCS_BUCKET}/${GCP_DIR}"
    # Make all files public
    - /google-cloud-sdk/bin/gsutil -m acl set -r "${CI_PROJECT_DIR}/gsutil-public.json" "gs://${GCS_BUCKET}/${GCP_DIR}**"
    # Make the redhat specific file only accessible for the Red Hat domain
    - /google-cloud-sdk/bin/gsutil -m acl set -r "${CI_PROJECT_DIR}/gsutil-redhat.json" "gs://${GCS_BUCKET}/**/redhat.js"
