variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  GCS_BUCKET: ocs-solver-dev
  GCS_PROJECT: apt-quarter-272014

default:
  image: google/cloud-sdk:alpine
  before_script:
    - apk update && apk add -u yarn
    - cd "$CI_PROJECT_DIR"
    - yarn install
  cache:
    paths:
      - node_modules

stages:
  - test
  - build
  - deploy


test:
  stage: test
  script:
    - ./node_modules/.bin/eslint --ext ".js,.ts" src/

build:
  stage: build
  script:
    - yarn build

push-to-google-storage:
  stage: deploy
  only:
    - main
  script:
    - yarn build
    - echo -n "${GCS_SA_KEY}" | base64 -d > /tmp/key.json && \
      gcloud auth activate-service-account --key-file=/tmp/key.json --project="${GCS_PROJECT}" && \
      rm /tmp/key.json
    - "./$CI_PROJECT_DIR/updateOnGoogle.sh"
