image:
  name: quay.io/mulbc/ocs-solver-builder:$CI_COMMIT_SHA
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
variables:
  CONTAINER_IMAGE_NAME: quay.io/mulbc/ocs-solver-builder
  DOCKER_HOST: unix:///var/run/docker.sock
  GCS_BUCKET: ocs-solver-dev
  GCS_PROJECT: apt-quarter-272014

stages:
  # - build
  # - lint
  - deploy

push-to-google-storage:
  stage: deploy
  image: google/cloud-sdk:alpine
  only:
    - cblum-dev

  script:
    - apk add -U npm
    - cd "$CI_PROJECT_DIR/backend"
    - npm install -g typescript
    - tsc --version
    - npm i
    - find "$CI_PROJECT_DIR/backend/src" -name "*.ts" | xargs tsc --outDir "$CI_PROJECT_DIR/backend/lib"
    - echo -n "${GCS_SA_KEY}" | base64 -d > /tmp/key.json
    - gcloud auth activate-service-account --key-file=/tmp/key.json --project="${GCS_PROJECT}"
    - rm /tmp/key.json
    - gsutil -m rsync -R -x "node_modules|src" "$CI_PROJECT_DIR/backend" "gs://$GCS_BUCKET"
