name: push to Google Storage

on:
  push:
    branches:
      - cblum-dev
    paths:
      - 'backend/**'

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: '12'

    - name: npm install
      working-directory: ./backend
      run: npm install

    - name: compile coffeescript
      working-directory: ./backend
      run: node_modules/.bin/coffee -c src/ -o lib/

    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        gsutil -m rsync -R backend gs://$GCS_BUCKET
